apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-q0m3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-q0m3
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-q0m3
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-q0m3
status:
  loadBalancer: {}
